[build]
  command = "npm install && npm run build"
  publish = ".next"
  environment = { NODE_ENV = "production", NODE_OPTIONS = "--max-old-space-size=4096", NEXT_PRIVATE_STANDALONE = "true" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NPM_FLAGS = "--include=dev"