[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_PRIVATE_STANDALONE = "true"
  NPM_FLAGS = "--include=dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"